### ISSUE TITLE
CentOS 7 HHVM 3.6 Test

### ISSUE THREAD

**Issue by rotor-head** [no1youknowz/hhvm-zeromq-ext#1]
build and test scripts are successful.

What's the preferred way to load the extension in HHVM?

**Comment by no1youknowz** [comment]
have a php.ini which does:

    hhvm.dynamic_extension_path = /usr/lib64/hhvm/extensions
    hhvm.dynamic_extensions[zmq] = zmq.so

**Comment by rotor-head** [comment]
Extension loads fine but breaks when our app makes a call to push. We're having to shelf HHVM for now as a result - no talent on the team to build or maintain this piece. It's a serious let down.

**Comment by no1youknowz** [comment]
What is your code?

I can push/pull just fine.

**Comment by rotor-head** [comment]
I do know it runs through a framework. I'm not the dev on this; he's been tasked with other priorities and can't contribute more on the issue. Wish I could help more but simply can't.

**Comment by no1youknowz** [comment]
I can't really help you then and it's not an issue if you can't replicate it.

I am using this extension in production right now.  So it does work to an extent.
