### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pjebs** [no1youknowz/hhvm-zeromq-ext#2]
Can you write instructions/documentation on how to install it on hhvm (for beginners)?
Also what are the current issues with running it on HHVM 3.7?

**Comment by no1youknowz** [comment]
I recommend you go to the wiki for the hhvm repo:  https://github.com/facebook/hhvm/wiki

There are some tests that don't pass.  Honestly, I don't recommend this for production.  I am using it for production but thats because I like being on the bleeding edge lol.
