### ISSUE TITLE
error building extension

### ISSUE THREAD

**Issue by digitalkaoz** [no1youknowz/hhvm-zeromq-ext#3]
the extension builds fine (with dep libzmq as state here https://github.com/yybirdcf/zmq-extension-for-hhvm)

but when i start HHVM (3.9.1) i get this error

`Systemlib systemlib.phpzmq' contains a fataling unit: Call-time pass-by-reference has been removed, 477`

any ideas?

**Comment by no1youknowz** [comment]
Sorry, due to time issues.  I am dropping development of this plugin.

I suggest using https://github.com/Orvid/php-zmq
